@Api.MOOC_HostAddress = http://localhost:5245

GET {{Api.MOOC_HostAddress}}/api/Category/GetCategory
Accept: application/json
Content-Type: application/json

###
POST {{Api.MOOC_HostAddress}}/api/Category/AddCategory
Accept: application/json
Content-Type: application/json
{
    "name": "New Category",
    "level": 2,
    "parentId": 1
}

###
PUT {{Api.MOOC_HostAddress}}/api/Category/UpdateCategory
Accept: application/json
Content-Type: application/json
{
    "id": 1,
    "name": "Updated Category",
    "level": 2,
    "parentId": 1
}

###
DELETE {{Api.MOOC_HostAddress}}/api/Category/DeleteCategory?Id=3
Accept: application/json
Content-Type: application/json

###
POST {{Api.MOOC_HostAddress}}/api/User/AddUser
Accept: application/json
Content-Type: application/json
{
    "userName": "john_doe2",
    "password": "password123",
    "email": "john.doe@example.com",
    "address": "123 Main St",
    "gender": 1,
    "access": 1
}

###
GET {{Api.MOOC_HostAddress}}/api/User/GetUsers
Accept: application/json
Content-Type: application/json

###
POST {{Api.MOOC_HostAddress}}/api/Login/Login
Content-Type: application/json
Accept: application/json

{
    "userName": "john_doe",
    "password": "password123"
}